version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'booking'
    volumes: 
      - 'db:/var/lib/postgresql/data'
      - './db:/usr/local/src/'
    ports: 
      - '5432:5432'
  # pgadmin: 
  #   image: dpage/pgadmin4
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: 'me@booking.ma'
  #     PGADMIN_DEFAULT_PASSWORD: 'secret'
  #   ports: 
  #     - '8888:80'
  #   volumes:
  #     - 'pgadmin:/var/lib/pgadmin'
  server:
    build:
      dockerfile: ./server.Dockerfile
    ports:
      - '80:8080'
    volumes: 
      - './build/libs:/usr/local/tomcat/webapps'

volumes: 
  db: 
  pgadmin: 

